package com.ngajiyuk.islamicmovie.Movie;

import java.util.ArrayList;

public class MovieData {
    public static String [][] data = new String[][]
        {
                {"Kisah Nabi Nuh AS","17 Juli 2019","Rate : 80 %","Setelah Nabi Adam wafat, manusia mulai tertipu oleh setan sehingga akhirnya mereka menyekutukan Allah. Maka Allah mengutus Nabi Nuh untuk menyadarkan kaumnya"+"\n Tanpa kenal lelah selama hampir 950 tahun, siang dan malam Nabi Nuh berusaha menyadarkan kaumnya. Namun kebanyakan kaumnya tidak mau beriman, bahkan mereka menantang agar Allah memberikan azab kepada kaumnya yang zalim dan melampaui batas itu."+"\n Allah menurunkan hujan yang tiada henti sehingga akhirnya menjadi banjir. Berapa lama hujan itu turun? Sedahsyat apa banjir yang menenggelamkan gunung tersebut dapat disaksikan dalam film animasi kisah Nabi Nuh AS ini.","https://pondokislami.com/wp-content/uploads/2017/04/kisah-nabi-nuh.jpg"},
                {"Kisah Nabi Yunus AS","18 Juli 2019","Rate : 81 %","Penduduk kota Ninawa menolak seruan Nabi Yunus dan mengusirnya. Nabi Yunus marah dan meninggalkan mereka seraya mengancam akan datangnya azab Allah SWT."+"\n Tak lama setelah kepergian Nabi Yunus, penduduk Ninawa pun bertobat. Sementara itu, Nabi Yunus pergi menumpang sebuah kapal, ternyata kapal tersebut mengalami goncangan yang hebat sebagai akibat diterpa oleh badai lautan. Nabi Yunus pun akhirnya diminta untuk menjadi korban dan menceburkan diri ke laut. Tidak berapa lama atas kuasa Allah SWT Nabi Yunus pun  ditelan oleh seekor ikan paus."+"\n Setelah beberapa hari di dalam perut ikan paus itu, Nabi Yunus akhirnya dimuntahkan ke sebuah pantai yang sepi. Dengan peristiwa itu Nabi Yunus pun menyadari kesalahan yang dilakukanya karena meninggalkan penduduk Ninawa padahal tugas dakwahnya belum selesai. Hingga akhirnya setelah menyadari kesalahan dan memohon ampun kepada Allah SWT, Nabi Yunus pun akhirnya kembali kepada kaumnya, yang pada saat itu telah bertobat akibat musibah yang mereka alami sepeninggal Nabi Yunus.","https://pondokislami.com/wp-content/uploads/2017/04/kisah-nabi-yunus.jpg"},
                {"Kisah Nabi Daud AS Melawan Jalut","19 Juli 2019","Rate : 79 %","Jalut adalah seorang pemimpin yang bertubuh besar seperti raksasa, kuat dan perkasa. Keahliannya dalam bela diri dan ilmu pedang menyebabkan tak seorang pun yang sanggup mengalahkannya. Namun kekuatan untuk menindas dan menyiksa Bangsa Bani Israil yang lemah dengan cara bengis dan kejam."+"\n Setelah sekian lama ditindas, dengan dipimpin oleh panglima Thalut, bangsa Bani Israil berangkat memerangi Jalut dan pasukannya. Namun meskipun mereka berhasil memporak porandakan pasukan Jalut, tidak seorang pun pasukan Thalut yang berani menghadapi Jalut."+"\n Seperti apakah kekuatan dan keperkasaan Jalut sehingga semua orang takut menghadapinya? Bagaimana akhir pertarungan ini? Adakah yang akan berani menghadapi Jalut? Temukan jawabannya dalam film ini.","https://pondokislami.com/wp-content/uploads/2017/04/kisah-nabi-daud.jpg"},
                {"Kisah Nabi Ibrahim AS dan Raja Namrudz","20 Juli 2019","Rate : 60 %","Bangsa Babilon telah lama hidup dalam kegelapan dan kesesatan. Penyembahan kepada patung dan berhala menyebabkan kerusakan akidah yang luar biasa."+"\n Penyembahan atas patung dan berhala menciptakan kehidupan yang penuh kerusakan dan menjadi hal yang biasa. Tua, muda, besar, kecil, lelaki dan perempuan, berperilaku hampir tiada beda. Nabi Ibrahim sang utusan, maju menentang kezaliman tersebut. Berdiri tegak di depan Raja Namrudz yang mengaku dirinya sebagai Tuhan."+"\n Nabi Ibrahim menyeru pada kebaikan dan jalan Tuhan pagi dan petang. Hingga ia merobohkan semua patung kecuali yang besar. Apakah yang akan dialami oleh Ibrahim akibat semua ini?"+"\n Bagaimana petualangannya? Akan kah ia selamat dari kemurkaan kaumnya? Bagaimana ia mghadapi kebengisan Namrudz yang kejam?\n" +
                        "\n" +
                        "Semuanya dapat disaksikan dalam film kartun islami Kisah Nabi Ibrahim dan Raja Namrudz ini.","https://pondokislami.com/wp-content/uploads/2017/04/kisah-nabi-ibrahim-dan-raja-namrudz.jpg"},
                {"Kisah Nabi Yusuf AS","21 Juli 2019","Rate : 90 %","Kisah Nabi Yusuf AS adalah sebuah kisah nabi Allah yang didalamnya terkandung banyak pelajaran dan penuh hikmah . Beliau dikaruniai wajah yang tampan dan berbagai keutamaan lainnya . Namun lantaran ketampanan dan keutamaan yang ada padanya itulah, ia mendapatkan banyak perlakuan buruk, antara lain dibuang kedalam sumur tua, menjadi budak dan dijebloskan kedalam penjara."+"\n Akan tetapi semua dilaluinya dengan penuh kesabaran dan keikhlasan. Sampai pada akhirnya kesabaran, kecerdasan dan kelembutan hati Nabi Yusuf AS menghantarkannya untuk menjadi seorang raja muda yang dihormati. Dengan atas izin Allah SWT Nabi Yusuf pun akhirnya dapat menyembuhkan ayahnya yang buta sebagai akibat usia dan kesedihan yang sangat dalam karena kehilangan anak kesayangannya yaitu Nabi Yusuf AS.","https://pondokislami.com/wp-content/uploads/2017/04/kisah-nabi-yusuf.jpg"},
                {"Kisah Nabi Sulaiman AS","22 Juli 2019","Rate : 89 %","Nabi Sulaiman mendapatkan kabar dari burung Hudhud tentang kerajaan Ratu Balqis yang menyembah matahari. Kemudian Nabi Sulaiman menyeru kepada Balqis untuk beriman kepada Allah. Akan tetapi Ratu Balqis menolakya. Kemudian menyiapkan pasukan untuk mendatangi istana Nabi Sulaiman."+"\n Di istana Nabi Sulaiman, ratu dikejutkan dengan keajaiban yang tidak masuk akal baginya, membuat hatinya luluh dan akhirnya beriman kepada Allah SWT.","https://pondokislami.com/wp-content/uploads/2017/04/kisah-nabi-sulaiman.jpg"},
                {"Kisah Nabi Adam AS","23 Juli 2019","Rate : 70 %","Film ini mengisahkan perjalanan Nabi Adam AS sebagai Nabi dan manusia pertama. Beliau diciptakan Allah untuk dijadikan khalifah di muka bumi."+"\n Atas perintah Allah, semua makhluk penghuni surga sujud menghormati Nabi Adam, kecuali iblis yang membangkang. Iblis merasa asal usulnya lebih baik, karena ia berasal dari api, sedangkan Nabi Adam dari tanah. Hal inilah yang membuat Iblis enggan mematuhi perintah Allah. Karena kesombongannya itulah, Iblis dikutuk oleh Allah, dan diusir dari surga."+"\n Meski demikian Iblis tetap pada kesombongannya dan bahkan bersumpah dan mengancam akan membujuk manusia keturunan Nabi Adam AS menuju jalan kesesatan bersamanya.","https://pondokislami.com/wp-content/uploads/2017/04/kisah-nabi-adam.jpg"},
                {"Kisah Nabi Musa dan Khidir AS","24 Juli 2019","Rate : 65 %","Nabi Musa AS mengaku di hadapan para pengikutnya bahwa ia adalah manusia terpandai di muka bumi ini. Namun, pernyataannya tersebut membuat Allah Swt. marah dan menurunkan sebuah ayat yang memerintahkan Nabi Musa berguru kepada seseorang yang bernama Khidir."+"\n Bagaimanakah perjalanan Nabi Musa dengan Khidir? Peristiwa apa saja yang mereka alami? Apakah Nabi Musa dapat memenuhi persyaratan yang diminta oleh Khidir?\n" +
                        "\n" +
                        "Temukan jawabannya dalam film ini dan selami hikmah dari perjalanan mereka.","https://pondokislami.com/wp-content/uploads/2017/04/kisah-nabi-musa-dan-khidir.jpg"},
                {"Kisah Nabi Muhammad Lahirnya sang utusan terakhir","25 Juli 2019","Rate : 90 %","Film ini mengisahkan sejarah kelahiran Nabi Muhammad SAW, hingga beliau diangkat menjadi rasul Allah SWT. Nabi Muhammad terlahir sebagai anak yatim. Ayahnya menginggal saat beliau masih dalam kandungan."+"\n Pada usia 6 tahun, Nabi Muhammad SAW menjadi yatim piatu. Ibunya meninggal dunia dalam perjalanan ziaranh ke makam Ayahnya di Yatsrib. Kemudian Nabi Muhammad diasuh kakeknya. Saat beliau umur 8 tahun, kakeknya meninggal dunia. Akhirnya beliau diasuh oleh pamannya Abu Thalib."+"\n Pada usia 12 tahun, Nabi Muhammad dibawa berniaga ke negeri Syam oleh Abu Thalib. Ketika tiba di Bashrah, beliau bertemu dengan pendeta Nasrani bernama Bukhira. Pendeta itu memberitahukan kepada Abu Thalib bahwa Nabi Muhammad memiliki tanda-tanda kenabian, Kemudian menyarankan untuk segera dibawa kembali pulang agar tidak dicelakai orang Romawi dan Yahudi"+"\n Bagaimanakah kisah selanjutnya hingga Nabi Muhammad diangkat menjadi Rasul? Simak kisah seru yang penuh nilai-nilai keteladanan dalam film ini.","https://pondokislami.com/wp-content/uploads/2017/04/kisah-nabi-muhammad-saw.jpg"},
                {"Kisah Nabi Muhammad SAW dan Pasukan Gajah serta Burung Ababil","26 Juli 2019","Rate : 98 %","Salah satu suku terkuat di negeri Arab yang merupakan keturunan Nabi Ibrahim, adalah Suku Quraish. Karena itu, tugas memelihara Kabah dan melayani haji diberikan kepada Suku Quraish. Tugas itu dipikul oleh kakek Nabi Muhammad SAW, Abdul Muthalib, sebagai pemimpin Quraish."+"\n Pada saat yang sama, Abrahah raja negeri Yaman telah membangun rumah ibadah terbesar di wilayah Arab. Namun tak seorang pun mengunjungi dan menghormatinya sebagaimana Ka’bah. Hal ini lah yang menyebabkan kegusaran Abrahah terhadap Kabah di Mekkah."+"\n Kemudian Abrahah dengan seluruh pasukan gajahnya menuju Mekkah bermaksud menghancurkan Kabah? Apa yang akan terjadi dengan Kabah? Apa pula yang akan menimpa Abrahah dan pasukan gajahnya?\n" +
                        "\n" +"Kisah seru penuh pelajaran berharga akan dapat disaksikan dalam film ini.",
                        "https://pondokislami.com/wp-content/uploads/2017/04/kisah-raja-abrahah-dan-burung-ababil.jpg"},
        };
    public static ArrayList<Movie> getListData(){
        ArrayList<Movie> list = new ArrayList<>();
        for (String[] aData : data){
            Movie movie = new Movie();
            movie.setName(aData[0]);
            movie.setDate(aData[1]);
            movie.setRate(aData[2]);
            movie.setDescrip(aData[3]);
            movie.setPhoto(aData[4]);

            list.add(movie);
        }
        return list;
    }
}
